# Generated by Django 4.2.7 on 2025-11-11 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Country name')),
                ('code', models.CharField(max_length=2, verbose_name='Country code')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Company name')),
            ],
            options={
                'verbose_name': 'Manufacturer',
                'verbose_name_plural': 'Manufacturers',
            },
        ),
        migrations.CreateModel(
            name='AndroidHeadUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Head unit name')),
                ('screen_size', models.CharField(choices=[('6.2', '6.2"'), ('7', '7"'), ('8', '8"'), ('9', '9"'), ('10.1', '10.1"'), ('10.4', '10.4"')], max_length=10, verbose_name='Screen size')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('description', models.TextField(verbose_name='Description')),
                ('android_version', models.CharField(max_length=50, verbose_name='Android version')),
                ('ram', models.CharField(max_length=20, verbose_name='RAM')),
                ('storage', models.CharField(max_length=20, verbose_name='Storage')),
                ('image', models.ImageField(upload_to='headunits/', verbose_name='Image')),
                ('in_stock', models.BooleanField(default=True, verbose_name='In stock')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mafony.country', verbose_name='Country')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mafony.manufacturer', verbose_name='Manufacturer')),
            ],
            options={
                'verbose_name': 'Android Head Unit',
                'verbose_name_plural': 'Android Head Units',
            },
        ),
    ]
